import React, { useEffect, useMemo, useState } from 'react';
import Window from './components/Window';
import ThreatMap from './components/ThreatMap';
import { certifications, experience, profile, projects, skills, socials } from './data/portfolio';

type AppId = 'identity'|'projects'|'files'|'security'|'skills'|'certs'|'career'|'resume'|'terminal'|'contact'|'settings'|'github'|'tryhackme'|'assistant'|'gallery'|'interview'|'threatmap';
type OpenWindow = { id: AppId; minimized: boolean; zIndex: number };

type GithubRepo = { id:number; name:string; description:string|null; language:string|null; stargazers_count:number; forks_count:number; html_url:string; updated_at:string };

const apps: { id: AppId; title: string; icon: string; hint:string }[] = [
  { id:'identity', title:'Identity', icon:'/icons/identity.svg', hint:'Operator profile' },
  { id:'projects', title:'Projects', icon:'/icons/projects.svg', hint:'Technical archive' },
  { id:'files', title:'File Explorer', icon:'/icons/files.svg', hint:'Browse workstation' },
  { id:'security', title:'Security Center', icon:'/icons/security.svg', hint:'SOC telemetry' },
  { id:'threatmap', title:'Threat Map', icon:'/icons/threat-map.svg', hint:'Global intelligence visualization' },
  { id:'skills', title:'Skills Monitor', icon:'/icons/skills.svg', hint:'Capability data' },
  { id:'certs', title:'Certifications', icon:'/icons/certs.svg', hint:'Verified records' },
  { id:'career', title:'Career', icon:'/icons/career.svg', hint:'Experience timeline' },
  { id:'resume', title:'Resume.pdf', icon:'/icons/resume.svg', hint:'View and download' },
  { id:'github', title:'GitHub Live', icon:'/icons/github.svg', hint:'Public repository feed' },
  { id:'tryhackme', title:'TryHackMe', icon:'/icons/tryhackme.svg', hint:'Training profile' },
  { id:'assistant', title:'Assistant.exe', icon:'/icons/assistant.svg', hint:'Ask about Tyler' },
  { id:'gallery', title:'Gallery', icon:'/icons/gallery.svg', hint:'Project visuals' },
  { id:'terminal', title:'BlackTerm', icon:'/icons/terminal.svg', hint:'Interactive shell' },
  { id:'contact', title:'Secure Comms', icon:'/icons/contact.svg', hint:'Contact Tyler' },
  { id:'settings', title:'Settings', icon:'/icons/settings.svg', hint:'Customize workstation' }
];

function BootScreen({ onDone }: { onDone:()=>void }) {
  const [line,setLine]=useState(0);
  const lines=['BLACKTERM BIOS v10.1.26','CPU............. AMD Ryzen platform detected','MEMORY.......... 32768 MB VERIFIED','GPU............. Graphics subsystem ONLINE','NETWORK......... ENCRYPTED VISITOR TUNNEL','SECURITY........ POLICY ENGINE ACTIVE','MOUNT........... /portfolio /projects /resume /threat-intel','AUTH............ TYLER DEPPA PROFILE FOUND','APPS............ AI SECURITY THREAT-MAP TERMINAL GITHUB RESUME','STARTING BLACKTERM DESKTOP...'];
  useEffect(()=>{ const timer=setInterval(()=>setLine(v=>{ if(v>=lines.length-1){clearInterval(timer);setTimeout(onDone,750);return v;} return v+1;}),260); return()=>clearInterval(timer);},[onDone]);
  return <div className="boot-screen"><div className="scanline"/><div className="boot-top"><div className="boot-mark">BT</div><div><div className="boot-logo">BLACKTERM <b>OS</b></div><small>PERSONAL CYBERSECURITY WORKSTATION</small></div></div><div className="boot-hardware">{lines.slice(0,line+1).map((item,i)=><p key={item}><span>{String(i+1).padStart(2,'0')}</span>{item}<b>OK</b></p>)}</div><div className="boot-progress"><i style={{width:`${((line+1)/lines.length)*100}%`}}/></div><footer>SECURE BOOT ENABLED // VISITOR MODE // BUILD 9.0.26</footer></div>;
}

function LoginScreen({ onLogin }:{onLogin:()=>void}) {
  return <div className="login-screen"><div className="login-orbit"/><div className="login-card"><div className="login-avatar">TD</div><small>AUTHORIZED OPERATOR</small><h1>{profile.name}</h1><p>{profile.title}</p><div className="login-status"><span>● ONLINE</span><b>WESTERN NEW YORK</b></div><button onClick={onLogin}>ENTER WORKSTATION <span>→</span></button><em>Protected read-only portfolio session</em></div></div>;
}

function SecurityCenter(){
 const [pulse,setPulse]=useState(36); const [ram,setRam]=useState(48);
 useEffect(()=>{const t=setInterval(()=>{setPulse(26+Math.floor(Math.random()*38));setRam(41+Math.floor(Math.random()*15));},1600);return()=>clearInterval(t)},[]);
 const events=['Visitor session authenticated','Resume archive mounted','GitHub endpoint available','Project index synchronized','Firewall policy verified'];
 return <div className="security-center"><div className="security-hero"><div className="shield-logo">⬡</div><div><small>SECURITY POSTURE</small><h2>All systems operational</h2><p>Read-only visitor environment protected by active workstation controls.</p></div><strong>LOW RISK</strong></div><div className="telemetry-grid">{[['CPU LOAD',`${pulse}%`],['MEMORY',`${ram}%`],['FIREWALL','ACTIVE'],['VPN','CONNECTED'],['INTEGRITY','100%'],['THREATS','0']].map(([a,b],i)=><article key={a}><small>{a}</small><b>{b}</b><div className="micro-chart">{[28,52,38,74,44,60,35,68].map((n,j)=><i key={j} style={{height:`${i<2?Math.max(12,n+(i?ram-48:pulse-36)):20}%`}}/>)}</div></article>)}</div><div className="event-log"><div className="section-title"><div><small>LIVE EVENT FEED</small><h3>Security operations log</h3></div><span>MONITORING</span></div>{events.map((event,i)=><div key={event}><time>{new Date(Date.now()-i*47000).toLocaleTimeString()}</time><span>INFO</span><p>{event}</p></div>)}</div></div>
}

function GithubApp(){
 const [repos,setRepos]=useState<GithubRepo[]>([]); const [status,setStatus]=useState('Connecting to public GitHub API...');
 useEffect(()=>{fetch('https://api.github.com/users/cojjjj/repos?sort=updated&per_page=8').then(r=>{if(!r.ok)throw new Error();return r.json()}).then(data=>{setRepos(data);setStatus('LIVE DATA')}).catch(()=>setStatus('Offline fallback — open GitHub for current repositories.'))},[]);
 return <div className="github-app"><div className="section-title"><div><small>PUBLIC SOURCE CONTROL</small><h2>cojjjj / repositories</h2></div><span>{status}</span></div><div className="github-summary"><article><strong>{repos.length||'—'}</strong><span>Recent repos loaded</span></article><article><strong>Python</strong><span>Primary project language</span></article><article><strong>Open</strong><span>Public profile status</span></article><a href="https://github.com/cojjjj" target="_blank" rel="noreferrer">OPEN FULL PROFILE ↗</a></div><div className="repo-list">{repos.length?repos.map(repo=><a key={repo.id} href={repo.html_url} target="_blank" rel="noreferrer"><div><strong>{repo.name}</strong><small>{repo.description||'Technical project repository'}</small></div><span>{repo.language||'Code'}</span><b>★ {repo.stargazers_count}　⑂ {repo.forks_count}</b></a>):<div className="loading-panel">GitHub data could not be loaded in this session.<br/><a href="https://github.com/cojjjj" target="_blank" rel="noreferrer">Open Tyler's GitHub profile ↗</a></div>}</div></div>
}

function TryHackMeApp(){
 return <div className="thm-app"><div className="thm-badge"><span>THM</span><small>TRAINING PROFILE</small></div><div className="section-title"><div><small>HANDS-ON CYBER TRAINING</small><h2>TryHackMe achievement record</h2></div><span>PORTFOLIO SNAPSHOT</span></div><div className="thm-stats"><article><strong>TOP 1%</strong><span>Global placement</span></article><article><strong>1000+</strong><span>Rooms completed</span></article><article><strong>DIAMOND</strong><span>Achievement tier</span></article><article><strong>108</strong><span>Capability score</span></article></div><div className="thm-note"><h3>Hands-on learning at scale</h3><p>Tyler has completed extensive practical training across offensive security, defensive operations, web exploitation, cloud security, networking, digital forensics, and incident response.</p><small>This panel uses portfolio data rather than claiming a live TryHackMe API connection.</small></div></div>
}


function FloatingAssistant({ onOpen }:{ onOpen:()=>void }){
 const [hint,setHint]=useState(true);
 useEffect(()=>{const t=setTimeout(()=>setHint(false),9000);return()=>clearTimeout(t)},[]);
 return <div className="floating-ai-wrap">
  {hint&&<button className="floating-ai-hint" onClick={onOpen}><strong>BLACKTERM AI</strong><span>Ask about Tyler, projects, skills, or open the resume.</span><b>OPEN ASSISTANT →</b></button>}
  <button className="floating-ai-orb" onClick={onOpen} aria-label="Open BLACKTERM AI assistant" title="Open BLACKTERM AI">
   <span className="orb-ring ring-one"/><span className="orb-ring ring-two"/><span className="orb-core"><i>BT</i></span><em>AI</em>
  </button>
 </div>;
}

function AssistantApp({openApp,activeContext}:{openApp:(id:AppId)=>void;activeContext?:AppId}){
 type ChatMessage={from:'user'|'ai';text:string;displayText?:string;actions?:{label:string;app:AppId}[]};
 type Phase={label:string;progress:number};
 const welcome="BLACKTERM AI online. I’ve indexed Tyler’s resume, projects, certifications, skills, experience, and public GitHub profile. Ask a question, describe a role you’re hiring for, or tell me which application to open.";
 const [messages,setMessages]=useState<ChatMessage[]>([{from:'ai',text:welcome,displayText:welcome,actions:[{label:'View projects',app:'projects'},{label:'Open resume',app:'resume'},{label:'Why hire Tyler?',app:'interview'}]}]);
 const [input,setInput]=useState('');
 const [thinking,setThinking]=useState(false);
 const [voice,setVoice]=useState(false);
 const [developer,setDeveloper]=useState(false);
 const [phase,setPhase]=useState<Phase|null>(null);
 const [memory,setMemory]=useState<string[]>([]);
 const quick=['Tell me about Tyler','I’m hiring for desktop support','Show Python projects','What certifications does Tyler have?','Open resume'];
 const speak=(text:string)=>{if(!voice||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.96;u.pitch=.88;window.speechSynthesis.speak(u)};
 const contextName=activeContext?apps.find(a=>a.id===activeContext)?.title:'';
 const buildAnswer=(q:string):ChatMessage=>{const s=q.toLowerCase().trim();
  const prior=memory.join(' ').toLowerCase();
  if(s.includes('developer mode')){setDeveloper(true);return{from:'ai',text:'Developer mode enabled. Knowledge source: local structured portfolio data. Actions: enabled. Conversation memory: session only. External model: not required. Hallucination guard: responses are limited to indexed information.'}};
  if(s.includes('open resume')||s==='resume'){openApp('resume');return{from:'ai',text:"Tyler’s resume is open in the document viewer. You can read it, print it, open it in a new browser tab, or download the PDF.",actions:[{label:'Resume.pdf',app:'resume'}]}};
  if(s.includes('threat map')||s.includes('global threat')||s==='threatmap'){openApp('threatmap');return{from:'ai',text:'Global Threat Intelligence is open. It is an interactive educational simulation featuring animated routes, threat filters, regional intelligence, and a rotating event stream.',actions:[{label:'Open Threat Map',app:'threatmap'}]}};
   if(s.includes('open github')||s==='github'){openApp('github');return{from:'ai',text:"GitHub Live is open with Tyler’s current public repositories and project descriptions.",actions:[{label:'GitHub Live',app:'github'}]}};
  if(s.includes('contact')||s.includes('email')||s.includes('reach')){openApp('contact');return{from:'ai',text:'Secure Comms is open. Tyler’s email and linked professional profiles are available there.',actions:[{label:'Contact Tyler',app:'contact'}]}};
  if(s.includes('interview me')||s.includes('practice interview')){openApp('interview');return{from:'ai',text:'Recruiter Mode is open. A future interview simulator can be added there; for now it presents Tyler’s strongest evidence for hiring decisions.',actions:[{label:'Open Recruiter Mode',app:'interview'}]}};
  if((s.includes('hiring')||s.includes('role')||s.includes('position'))&&(s.includes('desktop')||s.includes('help desk')||s.includes('support'))){openApp('career');return{from:'ai',text:'For a desktop support or help desk role, Tyler’s strongest fit comes from direct user support across Windows, macOS, and ChromeOS; hardware, software, printer, AV, and connectivity troubleshooting; ticket documentation; staff training; and calm communication with non-technical users. His cybersecurity studies add stronger security awareness and escalation judgment.',actions:[{label:'Experience',app:'career'},{label:'Resume',app:'resume'},{label:'Skills',app:'skills'}]}};
  if((s.includes('hiring')||s.includes('role')||s.includes('position'))&&(s.includes('security')||s.includes('soc')||s.includes('cyber'))){openApp('projects');return{from:'ai',text:'For an entry-level cybersecurity or SOC opportunity, Tyler’s strongest evidence is his Home SOC Detection Lab, BlackTerm PhishScan, extensive TryHackMe training, vulnerability-assessment work, Windows and Linux administration, and ability to explain technical findings clearly. His support background is valuable because security teams still depend on disciplined troubleshooting and communication.',actions:[{label:'Security projects',app:'projects'},{label:'TryHackMe',app:'tryhackme'},{label:'Certifications',app:'certs'}]}};
  if(s.includes('why')&&(s.includes('hire')||s.includes('choose'))){return{from:'ai',text:'Tyler combines real end-user support experience with hands-on cybersecurity development. He has supported Windows, macOS, ChromeOS, AV systems, printers, networking, and non-technical users while independently building security scanners, SOC labs, automation utilities, and Docker environments. That blend of communication, troubleshooting, and practical building makes him useful immediately and gives him a strong path into security-focused responsibilities.',actions:[{label:'Recruiter mode',app:'interview'},{label:'Resume',app:'resume'},{label:'Top projects',app:'projects'}]}};
  if(s.includes('hardest')&&prior.includes('blackterm')){return{from:'ai',text:'The most challenging part of BlackTerm PhishScan was coordinating many intelligence sources and failure states into one dependable workflow. URL validation, API limits, screenshots, DNS, WHOIS, SSL analysis, scoring, and report generation all had to remain useful even when one provider failed.'}};
  if((s.includes('technology')||s.includes('tech stack')||s.includes('used'))&&prior.includes('blackterm')){return{from:'ai',text:'BlackTerm PhishScan is primarily Python. Its workflow includes Rich for the terminal interface, browser automation for screenshots, WHOIS, SSL, DNS and IP lookups, VirusTotal and URLHaus intelligence, structured JSON data, and exportable HTML reports.',actions:[{label:'Project archive',app:'projects'},{label:'GitHub Live',app:'github'}]}};
  if(s.includes('python')){const names=projects.filter(p=>p.tech.some(t=>t.toLowerCase().includes('python'))).map(p=>p.name);openApp('projects');return{from:'ai',text:'Tyler’s Python-focused work includes '+(names.length?names.join(', '):'BlackTerm PhishScan, Walmart Calendar Sync OCR, SentinelWatch, and Log Integrity Checker')+'. These projects cover threat intelligence, OCR automation, monitoring, reporting, and security tooling.',actions:[{label:'Open project archive',app:'projects'},{label:'GitHub repositories',app:'github'}]}};
  if(s.includes('docker')||s.includes('container')){openApp('projects');return{from:'ai',text:'His container work includes a multi-service Docker environment with React, Node.js, MongoDB, Redis, Nginx, health checks, secrets, persistent volumes, and isolated networking.',actions:[{label:'View Docker project',app:'projects'}]}};
  if(s.includes('network')){return{from:'ai',text:'Tyler has experience troubleshooting connectivity, applying network fundamentals, working with DNS, DHCP, IP addressing, gateways, secure configurations, and building labs involving segmented services and monitored endpoints.',actions:[{label:'Skills monitor',app:'skills'},{label:'Experience',app:'career'}]}};
  if(s.includes('blackterm')||s.includes('phish')){openApp('projects');return{from:'ai',text:'BlackTerm PhishScan is a modular phishing and URL-intelligence framework. It combines risk scoring, screenshots, WHOIS, SSL, DNS, IP intelligence, VirusTotal, URLHaus, and exportable HTML/JSON reporting in a polished terminal workflow.',actions:[{label:'Project archive',app:'projects'},{label:'GitHub Live',app:'github'}]}};
  if(s.includes('project')){openApp('projects');return{from:'ai',text:"Tyler’s featured work includes BlackTerm PhishScan, Walmart Calendar Sync OCR, Home SOC Detection Lab, Multi-Service Docker Lab, SentinelWatch, and Log Integrity Checker. Together they demonstrate security tooling, automation, blue-team monitoring, infrastructure, and reporting.",actions:[{label:'Explore projects',app:'projects'},{label:'Open GitHub',app:'github'}]}};
  if(s.includes('cert')||s.includes('training')){openApp('certs');return{from:'ai',text:'Tyler’s listed training includes CompTIA ITF+, Certified Ethical Hacker, CompTIA PenTest+, Google Cybersecurity, IBM Cybersecurity Analyst, Cyber Defense training, plus extensive TryHackMe work placing him in the top 1%.',actions:[{label:'Certification archive',app:'certs'},{label:'TryHackMe profile',app:'tryhackme'}]}};
  if(s.includes('experience')||s.includes('job')||s.includes('career')){openApp('career');return{from:'ai',text:'Tyler has hands-on AV and IT help desk experience supporting staff and students, troubleshooting hardware, software, peripherals, connectivity, and live-event technology. He also brings customer-facing retail experience and is studying cybersecurity at Jamestown Community College.',actions:[{label:'Career timeline',app:'career'},{label:'Resume',app:'resume'}]}};
  if(s.includes('skill')||s.includes('language')||s.includes('know')){openApp('skills');return{from:'ai',text:'His strengths span desktop support, Windows and Linux administration, networking, customer communication, Python automation, Docker, vulnerability assessment, penetration testing fundamentals, incident response, and web technologies.',actions:[{label:'Skills monitor',app:'skills'},{label:'Projects',app:'projects'}]}};
  if(s.includes('summarize this')&&activeContext){return{from:'ai',text:`You are currently viewing ${contextName}. I can summarize indexed information about this application, or open related evidence.`,actions:[{label:contextName||'Current app',app:activeContext}]}};
  if(s.includes('about')||s.includes('who is')||s.includes('tell me about')){openApp('identity');return{from:'ai',text:'Tyler Deppa is a desktop support professional, cybersecurity student, and hands-on tool builder from Western New York. He focuses on practical troubleshooting, user support, automation, SOC labs, and offensive and defensive security projects.',actions:[{label:'Identity profile',app:'identity'},{label:'Projects',app:'projects'}]}};
  return{from:'ai',text:`I can answer questions about Tyler’s background, projects, Python or Docker work, certifications, experience, technical skills, resume, GitHub, contact details, or hiring fit${contextName?`. The active application is ${contextName}`:''}.`,actions:[{label:'About Tyler',app:'identity'},{label:'Projects',app:'projects'},{label:'Resume',app:'resume'}]};
 };
 const animateResponse=(response:ChatMessage)=>{const target=response.text;const entry={...response,displayText:''};setMessages(m=>[...m,entry]);let i=0;const timer=window.setInterval(()=>{i=Math.min(target.length,i+Math.max(2,Math.ceil(target.length/95)));setMessages(m=>m.map((msg,idx)=>idx===m.length-1?{...msg,displayText:target.slice(0,i)}:msg));if(i>=target.length){window.clearInterval(timer);speak(target)}},18)};
 const submit=(question=input)=>{const q=question.trim();if(!q||thinking)return;setMessages(m=>[...m,{from:'user',text:q,displayText:q}]);setMemory(m=>[...m.slice(-5),q]);setInput('');setThinking(true);const phases=[['Parsing request',22],['Searching resume and profile',51],['Matching projects and experience',78],['Preparing grounded response',100]] as const;phases.forEach(([label,progress],i)=>window.setTimeout(()=>setPhase({label,progress}),i*360));window.setTimeout(()=>{const response=buildAnswer(q);setPhase(null);setThinking(false);animateResponse(response)},phases.length*360+180)};
 return <div className="assistant-app assistant-pro ai-v3">
  <header><div className={`ai-orb ${thinking?'is-thinking':''}`}><i/><span>BT</span><em/></div><div><strong>BLACKTERM AI</strong><small>GROUNDED PORTFOLIO INTELLIGENCE</small></div><div className="assistant-head-actions"><button className={voice?'active':''} onClick={()=>setVoice(v=>!v)} title="Toggle voice">{voice?'VOICE ON':'VOICE OFF'}</button><span>● ONLINE</span></div></header>
  <div className="assistant-body"><aside className="assistant-status"><small>KNOWLEDGE STATUS</small>{[['Resume','LOADED'],['Projects','INDEXED'],['Experience','INDEXED'],['GitHub','CONNECTED']].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}<small>SESSION CONTEXT</small><div><span>Active app</span><b>{contextName||'DESKTOP'}</b></div><div><span>Memory</span><b>{memory.length} ITEMS</b></div><small>QUICK ACTIONS</small><button onClick={()=>openApp('resume')}>Open Resume</button><button onClick={()=>openApp('projects')}>Project Archive</button><button onClick={()=>openApp('interview')}>Recruiter Mode</button>{developer&&<section><small>DEVELOPER MODE</small><code>assistant: v3.0.0<br/>source: local index<br/>memory: session<br/>actions: enabled<br/>external API: none<br/>hallucination: guarded</code></section>}</aside>
   <section className="assistant-chat"><div className="chat-log">{messages.map((m,i)=><div key={i} className={m.from}><b>{m.from==='ai'?'BLACKTERM AI':'VISITOR'}</b><p>{m.displayText??m.text}{m.from==='ai'&&m.displayText!==undefined&&m.displayText.length<m.text.length&&<span className="typing-cursor">▋</span>}</p>{m.actions&&m.displayText===m.text&&<div className="chat-actions">{m.actions.map(a=><button key={a.label} onClick={()=>openApp(a.app)}>{a.label} ↗</button>)}</div>}</div>)}{thinking&&<div className="ai thinking phase-card"><b>BLACKTERM AI</b><p><span className="typing-dots"><i/><i/><i/></span>{phase?.label||'Initializing reasoning pipeline...'}</p><div className="ai-progress"><i style={{width:`${phase?.progress||8}%`}}/></div></div>}</div>
   <div className="suggested-questions">{quick.map(q=><button key={q} onClick={()=>submit(q)}>{q}</button>)}</div>
   <form onSubmit={e=>{e.preventDefault();submit()}}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask about Tyler, describe a role, or open an app..."/><button disabled={thinking}>{thinking?'THINKING':'SEND'}</button></form></section>
  </div>
 </div>;
}

function GalleryApp(){return <div><div className="section-title"><div><small>VISUAL ARCHIVE</small><h2>Project environments</h2></div><span>6 COLLECTIONS</span></div><div className="gallery-grid">{projects.map((p,i)=><article key={p.name}><div className={`gallery-art art-${i+1}`}><span>{String(i+1).padStart(2,'0')}</span><b>{p.type}</b></div><h3>{p.name}</h3><p>{p.tech.slice(0,3).join(' • ')}</p></article>)}</div></div>}

function InterviewApp({openApp}:{openApp:(id:AppId)=>void}){return <div className="interview-app"><span className="classified">RECRUITER ACCESS FILE</span><h1>Why Tyler?</h1><p>Tyler brings the rare mix of technical curiosity, real user-support experience, clear communication, and the discipline to keep building outside the classroom.</p><div className="interview-grid"><article><strong>01</strong><h3>Hands-on support</h3><p>Practical troubleshooting across devices, AV systems, software, networking, and end-user support.</p></article><article><strong>02</strong><h3>Security mindset</h3><p>Top 1% TryHackMe training plus offensive, defensive, SOC, and automation projects.</p></article><article><strong>03</strong><h3>Builder mentality</h3><p>Turns real problems into tools, labs, documentation, and portfolio-ready deliverables.</p></article></div><div className="thank-you"><h3>Thank you for exploring BLACKTERM OS.</h3><p>This workstation was built to demonstrate Tyler's ability to learn, design, troubleshoot, and communicate—not merely list it.</p><button onClick={()=>openApp('resume')}>OPEN RESUME</button><button onClick={()=>openApp('contact')}>CONTACT TYLER</button></div></div>}


function AmbientEngine({ enabled }:{enabled:boolean}){
 useEffect(()=>{
  if(!enabled) return;
  const AudioCtx=(window.AudioContext||(window as any).webkitAudioContext);
  if(!AudioCtx) return;
  const ctx=new AudioCtx();
  const master=ctx.createGain(); master.gain.value=.025; master.connect(ctx.destination);
  const osc=ctx.createOscillator(); const low=ctx.createBiquadFilter(); const drift=ctx.createOscillator(); const driftGain=ctx.createGain();
  osc.type='sine'; osc.frequency.value=52; low.type='lowpass'; low.frequency.value=180;
  drift.type='sine'; drift.frequency.value=.07; driftGain.gain.value=7;
  drift.connect(driftGain); driftGain.connect(osc.frequency); osc.connect(low); low.connect(master);
  osc.start(); drift.start();
  const resume=()=>ctx.state==='suspended'&&ctx.resume(); window.addEventListener('pointerdown',resume,{once:true});
  return()=>{window.removeEventListener('pointerdown',resume); try{osc.stop();drift.stop();ctx.close()}catch{}};
 },[enabled]);
 return null;
}

function ParticleField(){
 const dots=useMemo(()=>Array.from({length:34},(_,i)=>({
  left:`${(i*37)%100}%`, top:`${(i*61)%96}%`, size:1+(i%3), delay:`-${(i%11)*1.2}s`, duration:`${10+(i%9)}s`
 })),[]);
 return <div className="particle-field" aria-hidden="true">{dots.map((d,i)=><i key={i} style={{left:d.left,top:d.top,width:d.size,height:d.size,animationDelay:d.delay,animationDuration:d.duration}}/>)}</div>
}

function AppContent({id,openApp,notify,theme,setTheme,setMatrix,effects,setEffects,activeContext}:{id:AppId;openApp:(id:AppId)=>void;notify:(s:string)=>void;theme:string;setTheme:(s:string)=>void;setMatrix:(v:boolean)=>void;effects:{particles:boolean;glass:boolean;sound:boolean};setEffects:(v:any)=>void}){
 switch(id){
 case'identity':return <div className="identity-layout"><aside className="identity-card"><div className="avatar-ring"><div>TD</div></div><span className="online">● ONLINE</span><h1>{profile.name}</h1><p>{profile.title}</p><dl><div><dt>LOCATION</dt><dd>{profile.location}</dd></div><div><dt>CLEARANCE</dt><dd>PUBLIC PORTFOLIO</dd></div><div><dt>STATUS</dt><dd>AVAILABLE TO CONNECT</dd></div></dl></aside><section><div className="eyebrow">OPERATOR PROFILE // 001</div><h2>Building practical technology at the intersection of support and security.</h2><p className="lead">{profile.summary}</p><div className="stats-grid">{profile.stats.map(([a,b])=><article key={a}><strong>{b}</strong><span>{a}</span></article>)}</div><button className="primary-action" onClick={()=>openApp('projects')}>EXPLORE PROJECT ARCHIVE →</button></section></div>;
 case'projects':return <div><div className="section-title"><div><small>PROJECT ARCHIVE</small><h2>Selected technical operations</h2></div><span>{projects.length} RECORDS</span></div><div className="project-grid">{projects.map((p,i)=><article className="project-card" key={p.name}><div className="project-number">0{i+1}</div><div className="project-meta"><span>{p.type}</span><b>{p.status}</b></div><h3>{p.name}</h3><p>{p.description}</p><div className="tags">{p.tech.map(t=><span key={t}>{t}</span>)}</div><a href={p.github} target="_blank" rel="noreferrer">OPEN REPOSITORY ↗</a></article>)}</div></div>;
 case'files':return <FileExplorer openApp={openApp}/>; case'security':return <SecurityCenter/>; case'threatmap':return <ThreatMap/>; case'github':return <GithubApp/>; case'tryhackme':return <TryHackMeApp/>; case'assistant':return <AssistantApp openApp={openApp} activeContext={activeContext}/>; case'gallery':return <GalleryApp/>; case'interview':return <InterviewApp openApp={openApp}/>;
 case'skills':return <div><div className="section-title"><div><small>CAPABILITY TELEMETRY</small><h2>Technical skills monitor</h2></div><span>LIVE PROFILE</span></div><div className="skill-list">{skills.map(([n,s])=><div className="skill" key={n}><div><span>{n}</span><strong>{s}%</strong></div><div className="meter"><i style={{width:`${s}%`}}/></div></div>)}</div></div>;
 case'certs':return <div><div className="section-title"><div><small>VERIFIED TRAINING</small><h2>Certification archive</h2></div><span>{certifications.length} RECORDS</span></div><div className="cert-grid">{certifications.map(([n,c],i)=><article className="cert-card" key={n}><div className="cert-seal">0{i+1}</div><small>IDENTITY VERIFIED</small><h3>{n}</h3><p>{c}</p><footer><span>BLACKTERM RECORD</span><b>VERIFIED</b></footer></article>)}</div></div>;
 case'career':return <div><div className="section-title"><div><small>CAREER RECORD</small><h2>Experience and education</h2></div><span>ACTIVE TIMELINE</span></div><div className="timeline">{experience.map(x=><article key={x.role+x.company}><i className="timeline-dot"/><time>{x.period}</time><h3>{x.role}</h3><h4>{x.company}</h4><p>{x.details}</p></article>)}</div></div>;
 case'resume':return <div className="resume-viewer"><div className="pdf-toolbar"><div><span>▧</span><strong>Tyler-Deppa-Resume.pdf</strong></div><div><button onClick={()=>window.print()}>PRINT</button><a href="/Tyler-Deppa-Resume.pdf" target="_blank">OPEN</a><a href="/Tyler-Deppa-Resume.pdf" download>DOWNLOAD</a></div></div><iframe title="Tyler Deppa resume" src="/Tyler-Deppa-Resume.pdf"/></div>;
 case'terminal':return <TerminalApp openApp={openApp} notify={notify} setMatrix={setMatrix}/>;
 case'contact':return <div className="contact-app"><div className="section-title"><div><small>SECURE COMMUNICATIONS</small><h2>Connect with Tyler</h2></div><span>CHANNELS OPEN</span></div>{socials.map(([n,u],i)=><a key={n} href={u} target="_blank" rel="noreferrer"><span>{['⌘','▶','◉','in','@'][i]}</span><div><strong>{n}</strong><small>{u}</small></div><b>↗</b></a>)}</div>;
 case'settings':return <div className="settings"><div className="section-title"><div><small>WORKSTATION PERSONALIZATION</small><h2>Appearance and effects</h2></div><span>AUTO SAVED</span></div><h3>ACCENT THEME</h3><div className="theme-options">{[['blue','Electric Blue'],['cyan','Arctic Cyan'],['violet','Ultraviolet']].map(([v,n])=><button key={v} className={theme===v?'selected':''} onClick={()=>setTheme(v)}><i className={v}/><span>{n}</span><b>{theme===v?'ACTIVE':'SELECT'}</b></button>)}</div><h3>PREMIUM EFFECTS</h3><div className="theme-options effect-options">{([['particles','Ambient particles'],['glass','Glass blur'],['sound','Ambient sound']] as const).map(([key,label])=><button key={key} className={effects[key]?'selected':''} onClick={()=>setEffects(v=>({...v,[key]:!v[key]}))}><i className={key}/><span>{label}</span><b>{effects[key]?'ON':'OFF'}</b></button>)}</div><h3>VISUAL SUBSYSTEM</h3><div className="theme-options"><button onClick={()=>setMatrix(true)}><i className="matrix-dot"/><span>Matrix overlay</span><b>ENABLE</b></button><button onClick={()=>setMatrix(false)}><i className="blue"/><span>Standard grid</span><b>RESTORE</b></button></div></div>;
 }
}

export default function App(){
 const [stage,setStage]=useState<'boot'|'login'|'desktop'>('boot'); const [windows,setWindows]=useState<OpenWindow[]>([]); const [effects,setEffects]=useState({particles:true,glass:true,sound:false}); const [z,setZ]=useState(20); const [startOpen,setStartOpen]=useState(false); const [notification,setNotification]=useState(''); const [theme,setThemeState]=useState(localStorage.getItem('bt-theme')||'blue'); const [matrix,setMatrix]=useState(false); const [clock,setClock]=useState(new Date());
 useEffect(()=>{const t=setInterval(()=>setClock(new Date()),1000);return()=>clearInterval(t)},[]); useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('bt-theme',theme)},[theme]); useEffect(()=>{const saved=localStorage.getItem('bt-effects');if(saved)try{setEffects(JSON.parse(saved))}catch{}},[]); useEffect(()=>{localStorage.setItem('bt-effects',JSON.stringify(effects))},[effects]);
 const notify=(text:string)=>{setNotification(text);setTimeout(()=>setNotification(''),3200)};
 const openApp=(id:AppId)=>{setZ(v=>v+1);setWindows(old=>{const ex=old.find(w=>w.id===id);return ex?old.map(w=>w.id===id?{...w,minimized:false,zIndex:z+1}:w):[...old,{id,minimized:false,zIndex:z+1}]});setStartOpen(false)};
 const focus=(id:AppId)=>{setZ(v=>v+1);setWindows(w=>w.map(x=>x.id===id?{...x,zIndex:z+1}:x))};
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.ctrlKey&&e.code==='Space'){e.preventDefault();openApp('assistant')}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[z]);
 const activeId=useMemo(()=>windows.filter(w=>!w.minimized).sort((a,b)=>b.zIndex-a.zIndex)[0]?.id,[windows]);
 if(stage==='boot')return <BootScreen onDone={()=>setStage('login')}/>; if(stage==='login')return <LoginScreen onLogin={()=>{setStage('desktop');setTimeout(()=>{openApp('identity');notify('Welcome to BLACKTERM OS v10.1 — click the AI orb to explore')},250)}}/>;
 return <main className={`desktop theme-${theme} ${matrix?'matrix-mode':''} ${effects.glass?'glass-enabled':''}`} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--mouse-x',`${e.clientX-r.left}px`);e.currentTarget.style.setProperty('--mouse-y',`${e.clientY-r.top}px`)}} onContextMenu={e=>{e.preventDefault();openApp('settings')}}><AmbientEngine enabled={effects.sound}/>{effects.particles&&<ParticleField/>}<div className="mouse-light"/><div className="wallpaper-grid"/><div className="radar"/><div className="desktop-brand"><strong>BLACKTERM<span>OS</span></strong><small>PERSONAL CYBERSECURITY WORKSTATION // v10.1</small></div><div className="desktop-icons">{apps.slice(0,13).map(a=><button key={a.id} onDoubleClick={()=>openApp(a.id)} onClick={()=>openApp(a.id)}><span className="desktop-app-icon"><img src={a.icon} alt="" /></span><b>{a.title}</b></button>)}</div><aside className="desktop-widgets"><section><header>SYSTEM STATUS <span>LIVE</span></header><div><b>Firewall</b><strong>ACTIVE</strong></div><div><b>VPN</b><strong>CONNECTED</strong></div><div><b>Threats</b><strong>0</strong></div></section><section><header>OPERATOR</header><h3>Tyler Deppa</h3><p>Desktop Support • Cybersecurity • Builder</p><button onClick={()=>openApp('contact')}>CONNECT →</button></section><section><header>QUICK ACCESS</header><button onClick={()=>openApp('resume')}>Resume.pdf</button><button onClick={()=>openApp('github')}>GitHub Live</button><button onClick={()=>openApp('interview')}>/root/interview</button></section></aside>{matrix&&<div className="matrix-overlay">{Array.from({length:32},(_,i)=><span key={i} style={{left:`${i*3.2}%`,animationDelay:`-${(i%9)*.6}s`,animationDuration:`${4+(i%5)}s`}}>010011010101<br/>110100101100<br/>BLACKTERM<br/>001011010110<br/>CYBERSECURITY</span>)}</div>}
 {windows.map((w,index)=>{const a=apps.find(x=>x.id===w.id)!;return <Window key={w.id} title={a.title} icon={a.icon} active={activeId===w.id} minimized={w.minimized} zIndex={w.zIndex} startPosition={{x:150+(index%4)*34,y:55+(index%4)*27}} onFocus={()=>focus(w.id)} onClose={()=>setWindows(x=>x.filter(y=>y.id!==w.id))} onMinimize={()=>setWindows(x=>x.map(y=>y.id===w.id?{...y,minimized:true}:y))}><AppContent id={w.id} openApp={openApp} notify={notify} theme={theme} setTheme={setThemeState} setMatrix={setMatrix} effects={effects} setEffects={setEffects} activeContext={activeId}/></Window>})}
 {startOpen&&<div className="start-menu"><header><div className="mini-avatar">TD</div><div><strong>Tyler Deppa</strong><small>BLACKTERM OPERATOR</small></div><span>●</span></header><input placeholder="Search apps and files"/><div className="start-apps">{apps.map(a=><button key={a.id} onClick={()=>openApp(a.id)}><span className="menu-app-icon"><img src={a.icon} alt="" /></span><div><strong>{a.title}</strong><small>{a.hint}</small></div></button>)}</div><footer><span>BLACKTERM OS v10.1</span><button onClick={()=>setStage('login')}>LOCK</button></footer></div>}
 <FloatingAssistant onOpen={()=>openApp('assistant')}/>
 {notification&&<div className="notification"><span>BT</span><div><strong>SYSTEM NOTIFICATION</strong><p>{notification}</p></div></div>}
 <footer className="taskbar"><button className="start-button" onClick={()=>setStartOpen(v=>!v)}><b>BT</b><span>START</span></button><div className="task-items">{windows.map(w=>{const a=apps.find(x=>x.id===w.id)!;return <button key={w.id} className={activeId===w.id&&!w.minimized?'selected':''} onClick={()=>w.minimized?openApp(w.id):focus(w.id)}><span className="task-app-icon"><img src={a.icon} alt="" /></span><small>{a.title}</small></button>})}</div><div className="tray"><button className={`sound-toggle ${effects.sound?'on':''}`} onClick={()=>setEffects(v=>({...v,sound:!v.sound}))} title="Toggle ambient sound">{effects.sound?'◉':'○'}</button><span>⌁　◉　▥</span><div><strong>{clock.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</strong><small>{clock.toLocaleDateString()}</small></div></div></footer></main>
}
